In [1]:

import numpy as np

# -------- Sample Data Matrix --------
# Rows = samples, Columns = features
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print("Original Matrix X:\n", X)
print("Shape of X:", X.shape)

# =====================================
# SVD DECOMPOSITION
# X = U * Σ * V^T
# =====================================
U, S, Vt = np.linalg.svd(X, full_matrices=False)

print("\nMatrix U:\n", U)
print("Shape of U:", U.shape)

print("\nSingular Values (Σ):\n", S)
print("Shape of Σ:", S.shape)

print("\nMatrix V^T:\n", Vt)
print("Shape of V^T:", Vt.shape)

# =====================================
# DIMENSIONALITY REDUCTION (KEEP TOP k COMPONENTS)
# =====================================
k = 2  # number of components to keep

U_k = U[:, :k]
S_k = np.diag(S[:k])
Vt_k = Vt[:k, :]

# Reduced data
X_reduced = U_k @ S_k

print("\nReduced Data (k=2):\n", X_reduced)
print("Shape of Reduced Data:", X_reduced.shape)


Original Matrix X:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape of X: (4, 3)

Matrix U:
 [[-0.14087668 -0.82471435  0.53999635]
 [-0.34394629 -0.42626394 -0.65166613]
 [-0.54701591 -0.02781353 -0.31665681]
 [-0.75008553  0.37063688  0.42832658]]
Shape of U: (4, 3)

Singular Values (Σ):
 [2.54624074e+01 1.29066168e+00 2.40694596e-15]
Shape of Σ: (3,)

Matrix V^T:
 [[-0.50453315 -0.5745157  -0.64449826]
 [ 0.76077568  0.05714052 -0.64649464]
 [-0.40824829  0.81649658 -0.40824829]]
Shape of V^T: (3, 3)

Reduced Data (k=2):
 [[ -3.58705934  -1.06442721]
 [ -8.75770068  -0.55016253]
 [-13.92834202  -0.03589786]
 [-19.09898335   0.47836682]]
Shape of Reduced Data: (4, 2)
